name: finance
channels:
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - appdirs=1.4.3=py37h28b3542_0
  - appnope=0.1.0=py37_0
  - asn1crypto=1.3.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - beautifulsoup4=4.8.2=py37_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cffi=1.13.2=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py37_0
  - coloredlogs=10.0=py37_0
  - cryptography=2.8=py37ha12b0ac_0
  - decorator=4.4.2=py_0
  - flake8=3.7.9=py37_0
  - freetype=2.9.1=hb4e5f40_0
  - greenlet=0.4.15=py37h9bfed18_1
  - humanfriendly=6.1=py37_0
  - icu=58.2=h4b95b61_1
  - intel-openmp=2019.4=233
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.16.0=py37_0
  - joblib=0.14.1=py_0
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.37=ha441bb4_0
  - libxml2=2.9.9=hf6e021a_1
  - libxslt=1.1.33=h33a18ac_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - msgpack-python=0.6.1=py37h04f5b5a_1
  - mypy_extensions=0.4.3=py37_0
  - ncurses=6.1=h0a44026_1
  - neovim=0.3.1=py37_0
  - numpy=1.18.1=py37h7241aed_0
  - numpy-base=1.18.1=py37h6575580_1
  - openssl=1.1.1f=h1de35cc_0
  - pandas=1.0.0=py37h6c726b0_0
  - pandas-datareader=0.8.1=py_0
  - parso=0.6.1=py_0
  - pathspec=0.7.0=py_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=20.0.2=py37_1
  - prompt_toolkit=3.0.3=py_0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.19=py37_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.5.2=py_0
  - pynvim=0.4.1=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h359304d_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - readline=7.0=h1de35cc_5
  - regex=2020.2.20=py37h1de35cc_0
  - requests=2.22.0=py37_1
  - scikit-learn=0.22.1=py37h27c97d8_0
  - scipy=1.4.1=py37h9fa6033_0
  - setuptools=45.1.0=py37_0
  - six=1.14.0=py37_0
  - soupsieve=1.9.5=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - toml=0.10.0=py37h28b3542_0
  - tornado=6.0.3=py37h1de35cc_1
  - traitlets=4.3.3=py37_0
  - typed-ast=1.4.1=py37h1de35cc_0
  - typing_extensions=3.7.4.1=py37_0
  - urllib3=1.25.8=py37_0
  - wcwidth=0.1.8=py_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - cycler==0.10.0
    - deprecation==2.1.0
    - entrypoints==0.3
    - frozendict==1.2
    - idna==2.8
    - lxml==4.6.3
    - matplotlib==3.3.3
    - mccabe==0.6.1
    - mpl-finance==0.10.0
    - mplfinance==0.12.0a3
    - multitasking==0.0.9
    - packaging==20.9
    - pillow==8.1.0
    - pycodestyle==2.5.0
    - socketio-client-nexus==0.7.6
    - sseclient==0.0.27
    - temporal-cache==0.1.4
    - tzlocal==2.1
    - websocket-client==0.58.0
    - yfinance==0.1.59
